### ISSUE TITLE
如何在自己的录音的文件下进行预测

### ISSUE THREAD

**Issue by Lyantunm** [kuangcaomvp/speech-recognize#1]
如题，请问，输入的自己的录音在格式上有什么要求吗？

**Comment by kuangcaomvp** [comment]
> 如题，请问，输入的自己的录音在格式上有什么要求吗？

测试的输入录音文件为16k采样率的wav文件，其他没有要求

decoder.py 文件的225行full_path ='D4_750.wav' 替换成自己文件路径就可以测试了

**Comment by Lyantunm** [comment]
好的，谢谢您的回答，请问这个模型您用了哪些数据集进行训练？

**Comment by kuangcaomvp** [comment]
> 
> 
> 好的，谢谢您的回答，请问这个模型您用了哪些数据集进行训练？

aishell stcmd等一些网上通用数据集，加上自己录得一些真实场景数据集 大概2000小时的数据训练的

**Comment by Lyantunm** [comment]
> > 好的，谢谢您的回答，请问这个模型您用了哪些数据集进行训练？
> 
> aishell stcmd等一些网上通用数据集，加上自己录得一些真实场景数据集 大概2000小时的数据训练的

好的，谢谢您
