### ISSUE TITLE
词表问题

### ISSUE THREAD

**Issue by guofengming11** [kuangcaomvp/speech-recognize#10]
请问我的数据集里面有超出key.txt词表的字，这样直接送进网络训练会影响训练结果吗？我看到代码里好像如果超出了词表的话这一条就被弃用了，是这个意思么？确认一下
非常感谢

**Comment by kuangcaomvp** [comment]
> 请问我的数据集里面有超出key.txt词表的字，这样直接送进网络训练会影响训练结果吗？我看到代码里好像如果超出了词表的话这一条就被弃用了，是这个意思么？确认一下
> 非常感谢

不在字典内的数据会被过滤掉不会加入训练
