### ISSUE TITLE
每个epoch训练到进度条50%都会出现outofrange的error

### ISSUE THREAD

**Issue by guofengming11** [kuangcaomvp/speech-recognize#11]
每个epoch训练到进度条50%都会出现outofrange的error

![impicture_20210401_142324](https://user-images.githubusercontent.com/67827587/113252051-e44fa600-92f5-11eb-9a3c-97900c39724a.jpg)

**Comment by guofengming11** [comment]
请问这个是啥原因呢 没搞懂 感谢

**Comment by kuangcaomvp** [comment]
> 请问这个是啥原因呢 没搞懂 感谢
tensorflow 读取数据集是通过iterator.get_next()获取的 [calculate_mean_edit_distance_and_loss方法内]
如果数据集有6个批次的数据
for  i in range(6):
     sess.run(iterator.next_element)
可以迭代获取得到所有数据  超过6次循环在取数据就会抛出tf.errors.OutOfRangeError

train.py 内代码             pbar = tqdm(range(len(trainset)+1)) 
for i in pbar: 循环取数据    因为generate_data.py内有个过滤器
![image](https://user-images.githubusercontent.com/26867020/113431471-5fa47b00-940e-11eb-81e2-5d1e6ead4fe5.png)

所以pbar实际长度大于真实数据的长度 所以会抛出OutOfRangeError

![image](https://user-images.githubusercontent.com/26867020/113431593-911d4680-940e-11eb-98e8-bc9cc04f4bc0.png)
train.py内会通过捕获这个异常来判断数据集是否已经全部都取出来了 
你出现这个错误 我猜是你把抛异常的代码去掉了导致的 
train.py  os.environ['CUDA_VISIBLE_DEVICES'] = '1' 这行代码注释掉可以多gpu训练  

![image](https://user-images.githubusercontent.com/26867020/113431914-0c7ef800-940f-11eb-88f8-a94e44bb5bff.png)

代码改成  pbar = tqdm(range(len(trainset)//gpu数量+1)) 应该就不会50%就断了
