### ISSUE TITLE
训练报错 grads, all_vars = zip(*avg_tower_gradients)

### ISSUE THREAD

**Issue by Hachiiiiii** [kuangcaomvp/speech-recognize#13]
grads, all_vars = zip(*avg_tower_gradients)
ValueError: not enough values to unpack (expected 2, got 0)
这一行保证错误是什么原因呀？

**Comment by kuangcaomvp** [comment]
这行错误找原因很麻烦，计算loss的时候 loss为空导致的，如果代码和网络结构没动过的话，应该就是数据集制作有问题，可以检测下你的数据集，如果改过网络结构，有可能是网络有问题，我之前遇到过这个问题，我换了个模型，模型调用的tf.keras的api，结果就报了和你一样的这个错误，后来我吧代码修改调用tf.nn的api，问题就解决了，很神奇--！
不知道你的具体情况，上面的个人经历仅供参考。

**Comment by Hachiiiiii** [comment]
谢谢您的回复。
我什么都没改，莫名其妙的好了，也不知道什么原因。

**Comment by kuangcaomvp** [comment]
还有一种情况是你用的cpu训练，没有使用gpu也会报这个错

**Comment by Hachiiiiii** [comment]
那可能是的，之前训练的时候环境好像出了点问题，后面环境好了代码也可训练了
