### ISSUE TITLE
关于输入长度的问题

### ISSUE THREAD

**Issue by Lyantunm** [kuangcaomvp/speech-recognize#2]
作者您好，打扰您了，昨天测试了一下，发现您的模型效果很不错。这个算法好像有字数限制吧，输入较长一点多语音好像出现问题，请问这个限制大概是多大呢。

**Comment by kuangcaomvp** [comment]
音频文件提取的fbank特征是B*T*C，  encode做了4倍下采样 ，网络position 设置了1000，也就是T//4-1<1000音频应该都是可以的，大概在40s左右，这个是理论的最大时间
我训练的文件基本都是10S 20S的音频，估计长度超过30S效果就不会好了
要想识别长音频， 建议还是自己准备长音频文件重新训练， 或者使用vad将音频分割成短音频在识别

**Comment by Lyantunm** [comment]
好的，谢谢♪(･ω･)ﾉ
