### ISSUE TITLE
数据准备报错

### ISSUE THREAD

**Issue by Hachiiiiii** [kuangcaomvp/speech-recognize#5]
tensorflow.python.framework.errors_impl.UnimplementedError: Unsupported numpy type 5
	 [[{{node PyFunc}} = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_INT32], Tout=[DT_DOUBLE, DT_INT64, DT_INT32, DT_INT64, DT_INT32, DT_INT32, DT_INT64], token="pyfunc_3"](arg0, arg1, arg2, arg3)]]
	 [[node IteratorGetNext (defined at D:/PyCharm/SpeechRecognition/speech-recognize-master/generate_data.py:49)  = IteratorGetNext[output_shapes=[[?,?,40], [?,?], [?,?], [?,?], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

Process finished with exit code 1

想问一问大佬出现这个错误是什么原因，和您用的是一样的数据集

**Comment by kuangcaomvp** [comment]
> tensorflow.python.framework.errors_impl.UnimplementedError: Unsupported numpy type 5
> [[{{node PyFunc}} = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_INT32], Tout=[DT_DOUBLE, DT_INT64, DT_INT32, DT_INT64, DT_INT32, DT_INT32, DT_INT64], token="pyfunc_3"](arg0, arg1, arg2, arg3)]]
> [[node IteratorGetNext (defined at D:/PyCharm/SpeechRecognition/speech-recognize-master/generate_data.py:49) = IteratorGetNext[output_shapes=[[?,?,40], [?,?], [?,?], [?,?], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
> 
> Process finished with exit code 1
> 

PyFunc的输入输出数据类型不一样导致的 你看下calculation这个函数的输出类型是不是 Tout=[DT_DOUBLE, DT_INT64, DT_INT32, DT_INT64, DT_INT32, DT_INT32, DT_INT64] 这几个类型 
从你的报错信息来看 你的输出类型为output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32]
但是tf.py_func要求的数据类型为Tout=[DT_DOUBLE, DT_INT64, DT_INT32, DT_INT64, DT_INT32, DT_INT32, DT_INT64]
你修改62行代码为                     Tout=(tf.float, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32, tf.int32))
或者calculation这个函数里用tf.cast把不一致的数据类型转换下

**Comment by Hachiiiiii** [comment]
改出来了，多谢回复。
