### ISSUE TITLE
训练过程出现bug

### ISSUE THREAD

**Issue by guofengming11** [kuangcaomvp/speech-recognize#7]
训练代码在这一行出现了问题，请问是什么情况呢？

![image](https://user-images.githubusercontent.com/67827587/105790524-7d450680-5fbf-11eb-95cc-7c245a3dc054.png)

**Comment by kuangcaomvp** [comment]
不好意思啊 我看不到图片啊，你能不能复制黏贴我看下

**Comment by kuangcaomvp** [comment]
> 训练代码在这一行出现了问题，请问是什么情况呢？
> 
> ![image](https://user-images.githubusercontent.com/67827587/105790524-7d450680-5fbf-11eb-95cc-7c245a3dc054.png)

不好意思啊 我看不到图片啊，你能不能复制黏贴我看下

**Comment by guofengming11** [comment]
> > 训练代码在这一行出现了问题，请问是什么情况呢？
> > ![image](https://user-images.githubusercontent.com/67827587/105790524-7d450680-5fbf-11eb-95cc-7c245a3dc054.png)
> 
> 不好意思啊 我看不到图片啊，你能不能复制黏贴我看下

那个解决了，还有一个问题就是您是用什么数据训练出的model.pb模型呢，我用aishell，magicdata和aidatatang三个数据集合并训练了30个epoch，但是效果很不好，达不到你给的这个model.pb的效果

**Comment by kuangcaomvp** [comment]
> > > 训练代码在这一行出现了问题，请问是什么情况呢？
> > > ![image](https://user-images.githubusercontent.com/67827587/105790524-7d450680-5fbf-11eb-95cc-7c245a3dc054.png)
> > 
> > 
> > 不好意思啊 我看不到图片啊，你能不能复制黏贴我看下
> 
> 那个解决了，还有一个问题就是您是用什么数据训练出的model.pb模型呢，我用aishell，magicdata和aidatatang三个数据集合并训练了30个epoch，但是效果很不好，达不到你给的这个model.pb的效果
我的model.pb用了大概3000小时数据集训练的 你的三个通用数据太少了

**Comment by guofengming11** [comment]
请问可否发一个model.pb对应的ckpt模型呢 想接着您那个训练 感谢

**Comment by guofengming11** [comment]
> > > > 训练代码在这一行出现了问题，请问是什么情况呢？
> > > > ![image](https://user-images.githubusercontent.com/67827587/105790524-7d450680-5fbf-11eb-95cc-7c245a3dc054.png)
> > > 
> > > 
> > > 不好意思啊 我看不到图片啊，你能不能复制黏贴我看下
> > 
> > 
> > 那个解决了，还有一个问题就是您是用什么数据训练出的model.pb模型呢，我用aishell，magicdata和aidatatang三个数据集合并训练了30个epoch，但是效果很不好，达不到你给的这个model.pb的效果
> > 我的model.pb用了大概3000小时数据集训练的 你的三个通用数据太少了

请问可否发一个model.pb对应的ckpt模型呢 想接着您那个训练 感谢

**Comment by Hachiiiiii** [comment]
你好请问您一开始出现的那个错误怎么解决的呀！！我也遇到了一样的错误
grads, all_vars = zip(*avg_tower_gradients)
ValueError: not enough values to unpack (expected 2, got 0)
就是这个错误
