### ISSUE TITLE
关于model.pb

### ISSUE THREAD

**Issue by guofengming11** [kuangcaomvp/speech-recognize#8]
请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢

**Comment by kuangcaomvp** [comment]
> 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
模型我放在百度网盘了 地址如下 
链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q 
提取码：ryqc

**Comment by guofengming11** [comment]
> > 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
> > 模型我放在百度网盘了 地址如下
> > 链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q
> > 提取码：ryqc

您好，我想在你给的这个ckpt文件的基础上继续训练，但是在train.py中restore一直不成功，是不是你给的这个ckpt文件与模型对应不上啊？
多谢

**Comment by kuangcaomvp** [comment]
> > > 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
> > > 模型我放在百度网盘了 地址如下
> > > 链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q
> > > 提取码：ryqc
> 
> 您好，我想在你给的这个ckpt文件的基础上继续训练，但是在train.py中restore一直不成功，是不是你给的这个ckpt文件与模型对应不上啊？
> 多谢

你把train.py里面restore模型的地方上下try抓取异常的代码注释掉，运行看具体报什么错误，你把错误信息贴我看下，ckpt文件与模型是对应的，我猜测有可能你改了字典key.py 没有具体的报错信息 我也不知道具体什么原因

**Comment by guofengming11** [comment]
> > > > 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
> > > > 模型我放在百度网盘了 地址如下
> > > > 链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q
> > > > 提取码：ryqc
> > 
> > 
> > 您好，我想在你给的这个ckpt文件的基础上继续训练，但是在train.py中restore一直不成功，是不是你给的这个ckpt文件与模型对应不上啊？
> > 多谢
> 
> 你把train.py里面restore模型的地方上下try抓取异常的代码注释掉，运行看具体报什么错误，你把错误信息贴我看下，ckpt文件与模型是对应的，我猜测有可能你改了字典key.py 没有具体的报错信息 我也不知道具体什么原因

这是报错图：感谢感谢
![impicture_20210222_192604](https://user-images.githubusercontent.com/67827587/108702325-0fe7af80-7544-11eb-8271-69df1b2c6688.jpg)
我没有改过key文件。。。感谢感谢

**Comment by kuangcaomvp** [comment]
> > > > > 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
> > > > > 模型我放在百度网盘了 地址如下
> > > > > 链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q
> > > > > 提取码：ryqc
> > > 
> > > 
> > > 您好，我想在你给的这个ckpt文件的基础上继续训练，但是在train.py中restore一直不成功，是不是你给的这个ckpt文件与模型对应不上啊？
> > > 多谢
> > 
> > 
> > 你把train.py里面restore模型的地方上下try抓取异常的代码注释掉，运行看具体报什么错误，你把错误信息贴我看下，ckpt文件与模型是对应的，我猜测有可能你改了字典key.py 没有具体的报错信息 我也不知道具体什么原因
> 
> 这是报错图：感谢感谢
> ![impicture_20210222_192604](https://user-images.githubusercontent.com/67827587/108702325-0fe7af80-7544-11eb-8271-69df1b2c6688.jpg)
> 我没有改过key文件。。。感谢感谢

对不住了 ，大兄弟 ，模型我改了我忘记了，你更新下代码应该就能跑了

**Comment by guofengming11** [comment]
> > > > > > 请问作者，可以提供一下model.pb对应的ckpt模型文件么 ？ 非常感谢
> > > > > > 模型我放在百度网盘了 地址如下
> > > > > > 链接：https://pan.baidu.com/s/1_CgXG3AvBDrXGTRr5_Rv8Q
> > > > > > 提取码：ryqc
> > > > 
> > > > 
> > > > 您好，我想在你给的这个ckpt文件的基础上继续训练，但是在train.py中restore一直不成功，是不是你给的这个ckpt文件与模型对应不上啊？
> > > > 多谢
> > > 
> > > 
> > > 你把train.py里面restore模型的地方上下try抓取异常的代码注释掉，运行看具体报什么错误，你把错误信息贴我看下，ckpt文件与模型是对应的，我猜测有可能你改了字典key.py 没有具体的报错信息 我也不知道具体什么原因
> > 
> > 
> > 这是报错图：感谢感谢
> > ![impicture_20210222_192604](https://user-images.githubusercontent.com/67827587/108702325-0fe7af80-7544-11eb-8271-69df1b2c6688.jpg)
> > 我没有改过key文件。。。感谢感谢
> 
> 对不住了 ，大兄弟 ，模型我改了我忘记了，你更新下代码应该就能跑了

请问作者，在您用的数据集基础上，model.pb还有提升的空间吗？

**Comment by kuangcaomvp** [comment]
> 请问作者，在您用的数据集基础上，model.pb还有提升的空间吗？

我这个模型只用了3000小时数据，现在行业内训练基本都是上万小时起步的，如果有大量数据集的话提升空间还是很大的，我没有那么大量的数据集，具体的还是要训练做实验看看效果

提高识别率也可以从其他方面入手，比如用rnnnoise等模型先对语音做个降噪处理，在走识别模型也能提高识别率，或者把模型换成其他试试比如换成transformer-xl/conformer/reformer这些transformer变种应该会有提升
包括增加模型维度，我现在用的模型dim是256，layers都是6 ，transformer论文上dim是512 layers是12，transformer参数增加也能提高识别率，就是显存会消耗比较大，训练识别速度上会变慢，比较吃资源。
