### ISSUE TITLE
采样率

### ISSUE THREAD

**Issue by guofengming11** [kuangcaomvp/speech-recognize#9]
请问作者，训练数据采样频率只能是16000吗？
我现在有的数据采样率是22k的直接拿进网络训练有影响吗？
非常感谢

**Comment by kuangcaomvp** [comment]
> 请问作者，训练数据采样频率只能是16000吗？
> 我现在有的数据采样率是22k的直接拿进网络训练有影响吗？
> 非常感谢

采样率根据自己的数据定的，我用的数据都是16k采样率，用其他采样率数据训练没有影响
